# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45096dac8873cd7aa8f07a73345754ba61d42abdf6d2fd4d00f9ff262756860882f4d9a625ed3f667528647b203f38b80c713aaaf018372a567f171568a3607a

test:
  secret_key_base: 7f3749f5cb78efec65a14f4f683607d7fb4fb9822531582e35c6172dc8e1e93554275f429f834fe06559a71ccc25a1f5567fcc5ce81fe5c71afb6b46c42ba4c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
